
package main;

import org.kordamp.ikonli.carbonicons.CarbonIcons;
import org.kordamp.ikonli.swing.FontIcon;

/**
 *
 * @author Mustafa Mohamed
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
        int iconSize = 16;
        
        FontIcon fontIcon = FontIcon.of(CarbonIcons.PLAY);
        fontIcon.setIconSize(iconSize);
        jButtonPronunciation.setIcon(fontIcon);
        jButtonPronunciation.setText("");
        jButtonPronunciation.setToolTipText("Pronunciation");
        
        FontIcon iconPrevious = FontIcon.of(CarbonIcons.PREVIOUS_OUTLINE);
        iconPrevious.setIconSize(iconSize);
        jButtonPrevious.setIcon(iconPrevious);
        jButtonPrevious.setToolTipText("Previous search");
        jButtonPrevious.setText("");
        
        FontIcon iconNext = FontIcon.of(CarbonIcons.NEXT_OUTLINE);
        iconNext.setIconSize(iconSize);
        jButtonNext.setIcon(iconNext);
        jButtonNext.setToolTipText("Next search");
        jButtonNext.setText("");
        
        FontIcon iconBookmark = FontIcon.of(CarbonIcons.BOOKMARK);
        iconBookmark.setIconSize(iconSize);
        jButtonBookmark.setIcon(iconBookmark);
        jButtonBookmark.setToolTipText("Bookmark this word");
        jButtonBookmark.setText("");
        
        jTextFieldSearch.putClientProperty("JTextField.placeholderText", "Search");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldSearch = new javax.swing.JTextField();
        jButtonBookmark = new javax.swing.JButton();
        jButtonPronunciation = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jButtonPrevious = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wiktionary Java");

        jButtonBookmark.setText("Bookmark");
        jButtonBookmark.setToolTipText("Bookmark current search");

        jButtonPronunciation.setText("Pronunciation");

        jButtonNext.setText("Next");

        jButtonPrevious.setText("Previous");

        jTextPane.setEditable(false);
        jScrollPane1.setViewportView(jTextPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPrevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPronunciation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBookmark)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBookmark)
                    .addComponent(jButtonPronunciation)
                    .addComponent(jButtonNext)
                    .addComponent(jButtonPrevious))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBookmark;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrevious;
    private javax.swing.JButton jButtonPronunciation;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JTextPane jTextPane;
    // End of variables declaration//GEN-END:variables
}
